function scenario = createVillageCrossing(cfg)
%CREATEVILLAGECROSSING Create deterministic lane-agnostic scenario state.
rng(cfg.seed, 'twister');
sc = cfg.scenario;
x = (0:sc.boundarySampleM:sc.roadLengthM)';
[leftY, rightY] = pathweaver.core.roadBounds(x, sc);
scenario = struct('name', sc.name, 'timeS', 0, 'roadXWorldM', x, ...
    'leftBoundaryWorldM', [x leftY], 'rightBoundaryWorldM', [x rightY], ...
    'agents', [rmfield(sc.pedestrian, {'triggerEgoXM','crossingSpeedMps'}) ...
        sc.twoWheeler], 'staticObstacles', sc.pothole, ...
    'goalPositionWorldM', sc.goalPositionWorldM, ...
    'pedestrianTriggered', false, 'seed', cfg.seed);
end
