function scenario = createVillageCrossing(cfg)
%CREATEVILLAGECROSSING Create deterministic lane-agnostic scenario state.
rng(cfg.seed, 'twister');
sc = cfg.scenario;
x = (0:sc.boundarySampleM:sc.roadLengthM)';
[leftY, rightY] = pathweaver.core.roadBounds(x, sc);
pedestrian = sc.pedestrian;
twoWheeler = sc.twoWheeler;
pedestrian.positionWorldM(1) = pedestrian.positionWorldM(1) + ...
    sc.longitudinalJitterStdM*randn();
twoWheeler.positionWorldM(1) = twoWheeler.positionWorldM(1) + ...
    sc.longitudinalJitterStdM*randn();
scenario = struct('name', sc.name, 'timeS', 0, 'roadXWorldM', x, ...
    'leftBoundaryWorldM', [x leftY], 'rightBoundaryWorldM', [x rightY], ...
    'agents', [rmfield(pedestrian, {'triggerEgoXM','crossingSpeedMps'}) ...
        twoWheeler], 'staticObstacles', sc.pothole, ...
    'goalPositionWorldM', sc.goalPositionWorldM, ...
    'pedestrianTriggered', false, 'seed', cfg.seed);
end
